#Rama que va a disparar el pipeline (donde están las pruebas)
trigger:
- master

#pool de agentes que provee azure cloud (siempre se crea un contenedor) <- máquina virtual
pool:
  vmImage: ubuntu-latest

#Pasos del pipeline
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run test-ci
    npm run build
  displayName: 'npm install, test and build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarCloud'
    organization: 'santiagogm19'
    scannerMode: 'CLI'
    configMode: 'file'

- task: SonarCloudAnalyze@1
  displayName: 'run SonarCloud'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'